return {
  {
    "2KAbhishek/pickme.nvim",
    cmd = "PickMe",
    event = "VeryLazy",
    dependencies = {
      "folke/snacks.nvim",
      "nvim-telescope/telescope.nvim",
      "ibhagwan/fzf-lua",
    },
    opts = {
      picker_provider = "snacks",
      add_default_keybindings = false,
    },
  },
  -- {
  --   "2kabhishek/markit.nvim",
  --   config = load_config("tools.markit"),
  --   event = { "BufReadPost", "BufNewFile" },
  -- },
  {
    "2KAbhishek/octohub.nvim",
    cmd = {
      "OctoRepos",
      "OctoReposByCreated",
      "OctoReposByForks",
      "OctoReposByIssues",
      "OctoReposByLanguages",
      "OctoReposByNames",
      "OctoReposByPushed",
      "OctoReposBySize",
      "OctoReposByStars",
      "OctoReposByUpdated",
      "OctoReposTypeArchived",
      "OctoReposTypeForked",
      "OctoReposTypePrivate",
      "OctoReposTypeStarred",
      "OctoReposTypeTemplate",
      "OctoRepo",
      "OctoStats",
      "OctoActivityStats",
      "OctoContributionStats",
      "OctoRepoStats",
      "OctoProfile",
      "OctoRepoWeb",
    },
    keys = {
      "<localleader>goa",
      "<localleader>goA",
      "<localleader>gob",
      "<localleader>goc",
      "<localleader>gof",
      "<localleader>goF",
      "<localleader>gog",
      "<localleader>goi",
      "<localleader>gol",
      "<localleader>goo",
      "<localleader>gop",
      "<localleader>goP",
      "<localleader>gor",
      "<localleader>gos",
      "<localleader>goS",
      "<localleader>got",
      "<localleader>goT",
      "<localleader>gou",
      "<localleader>goU",
      "<localleader>gow",
    },
    dependencies = {
      "2kabhishek/utils.nvim",
      "2kabhishek/pickme.nvim",
    },
  },
}
